name: Codecov

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: latest-stable

    - name: Generate test fixtures
      run: ./prepareTestResults.sh

    - name: Test with coverage
      run: swift test --enable-code-coverage

    - name: Export Coverage
      run: |
        xcrun llvm-cov export -format="lcov" \
        .build/debug/XCTestHTMLReportPackageTests.xctest/Contents/MacOS/XCTestHTMLReportPackageTests \
        -instr-profile .build/debug/codecov/default.profdata > info.lcov

    - uses: codecov/codecov-action@v4
      with:
        files: info.lcov
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
