# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Download Test Resources
      run: |
        aws s3 cp --recursive s3://xctesthtmlreport/ ./Tests/XCTestHTMLReportTests/Resources/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
    - name: Extract Test Resources
      run: |
        find Tests/XCTestHTMLReportTests/Resources -name '*.tar.gz' -execdir tar -xzvf '{}' \;
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0        
      with:
        xcode-version: ^15
    - name: Run tests
      run: xcrun swift test -v
