# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download Test Resources
      run: |
        aws s3 cp --recursive s3://xctesthtmlreport/ ./Tests/XCTestHTMLReportTests/Resources/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY_ID }}
        AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
    - name: ls
      run: ls ./Tests/XCTestHTMLReportTests/Resources
    # - name: Build
    #   run: swift build -v
    # - name: Run tests
    #   run: swift test -v
